command: ["uv", "run", "dspy-forge", "--workers", "4"]
# databricks apps listen by default on port 8000

env:
  - name: STORAGE_BACKEND
    value: "databricks"
  - name: ARTIFACTS_PATH
    valueFrom: "artifacts_path"